FROM golang:latest
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64
WORKDIR /app/Golang-poc
COPY go.mod .
COPY go.sum .
COPY . .
RUN go get
RUN go mod download
RUN go build -o main .
EXPOSE 8080
# Run the executable
CMD ["./main"]